services:
  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - visa_types
    volumes:
      - .data/postgres:/var/lib/postgresql/data

  app:
    image: ghcr.io/visatypes/backend:v1.0.1
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - visa_types

networks:
  visa_types: